### ISSUE TITLE
Consider merging with similar projects

### ISSUE THREAD

**Issue by riccardomc** [contentful-labs/kube-secret-syncer#46]
Hello! I am the original maintainer of a [very similar project](https://github.com/ContainerSolutions/externalsecret-operator), now maintained by my colleagues. I would like to bring to your attention an attempt to a coordinated effort that aims at bringing together all similar projects:

https://github.com/godaddy/kubernetes-external-secrets/issues/47

The main idea is to have a common, standardized CRD for secrets in order to make switching from one project to the other easy and eventually converge to a single solution.

I appreciate there is value in having multiple solutions for the same problem, but the community could also benefit from a coordinated effort in this space.

Keep up the good work!

**Comment by knelasevero** [comment]
Common CRD being discussed here :smiley: :
https://github.com/godaddy/kubernetes-external-secrets/pull/477

**Comment by yanivpaz** [comment]
Does kubernetes-external-secrets support IRSA ? ( IAM role for service account )

 there is also a great solution from Cyberark -
its lately presented by @jodyhuntatx  - you can see this [here](https://www.youtube.com/watch?v=zpaDajHKab4&feature=youtu.be&t=1652) 
which leverage init container pattern rather than Operator.

**Comment by yannh** [comment]
Hello there :wave:  First - work on kube-secret-syncer started last year, so a few of the solutions present nowadays didn't exist at the time! We were aware though of several existing solutions when we decided to start this one. All tools we looked at would have required considerable changes to implement the features we needed - and because we would not have direct access to the upstream repository, it would have required a lot of good will, time & collaboration from the upstream maintainers, which would have been a risky bet. I appreciate though that the plethora of solutions make it more difficult to pick a good one. 

This project does seem interesting: https://github.com/kubernetes-sigs/secrets-store-csi-driver - I would recommend keeping an eye on it. 

As with other Kubernetes components (CNIs being a good example) - I would expect a number of solutions to compete until one ends up being better for most use-cases and win the users hearts :)

Thank you for pointing out the other projects! I (personnally) will keep an eye on the common CRD effort, might participate, but I don't believe we have the manpower to contribute much to this at the moment, so I will be closing this ticket. Maybe we'll revisit in the future :+1:
